name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # The workflow triggers when code is pushed to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to another OS if needed

    steps:
    # Step 1: Checkout the code
    - name: Check out repository
      uses: actions/checkout@v2

    # Step 2: Login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm64 -t pratikdhore/gatekeep:latest . --push
        
  deploy:
    runs-on: ubuntu-latest

    needs: build
    steps:
    # Step 5: SSH into your VM and deploy the Docker image
    - name: SSH into VM and deploy Docker image
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: 22
        script: |
          docker pull pratikdhore/gatekeep:latest
          docker stop gatekeepContainer || true
          docker rm gatekeepContainer || true
          docker run -d --name gatekeepContainer -p 8080:8080 pratikdhore/gatekeep:latest
