name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # The workflow triggers when code is pushed to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to another OS if needed
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      ROBOFLOW_API_KEY: ${{ secrets.ROBOFLOW_API_KEY }}
      
    steps:
    # Step 1: Checkout the code
    - name: Check out repository
      uses: actions/checkout@v2

    # Step 2: Set up QEMU
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # Step 3: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 4: Login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Build and push multi-platform Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: pratikdhore/gatekeep:latest
        platforms: linux/amd64,linux/arm64

  deploy:
    runs-on: ubuntu-latest

    needs: build
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      ROBOFLOW_API_KEY: ${{ secrets.ROBOFLOW_API_KEY }}
    steps:
    # Step 6: SSH into your VM and deploy the Docker image
    - name: SSH into VM and deploy Docker image
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: 22
        script: |
          # Pull the latest image for GateKeep
          docker pull pratikdhore/gatekeep:latest

          # Stop & remove the old container if it exists
          docker stop gatekeepContainer || true
          docker rm gatekeepContainer || true

          # Create a Docker network if not already created
          docker network create app-network || true

          # Run the GateKeep container INSIDE the network (no port exposed)
          docker run -d --name gatekeepContainer --network app-network \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            -e ROBOFLOW_API_KEY="${{ secrets.ROBOFLOW_API_KEY }}" \
            pratikdhore/gatekeep:latest

          # Start or restart the NGINX reverse proxy container (assumes nginx.conf is already in place)
          docker stop nginxProxy || true
          docker rm nginxProxy || true
          docker run -d --name nginxProxy --network app-network \
            -v /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf:ro \
            -p 80:80 nginx
